{% set name = "scikit-sundae" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 8e9e209d0811e4fdc9b8e0a28e10fc6b8d2a1c3ed3e660024c1026fde8e50e7c

build:
  script:
    - export SUNDIALS_PREFIX=$PREFIX          # [not win]
    - set "SUNDIALS_PREFIX=%LIBRARY_PREFIX%"  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python  # [build_platform != target_platform]
    - setuptools  # [build_platform != target_platform]
    - cython  # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]
    - sundials >=7.1,<7.2  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - libblas
    - pip
    - sundials >=7.1,<7.2
  run:
    - python
    - numpy
    - sundials >=7.1,<7.2

test:
  imports:
    - numpy
    - sksundae
  files:
    - integrate.py
  commands:
    - python integrate.py

about:
  home: https://github.com/NREL/scikit-sundae
  summary: 'SUNDIALS bindings to differential aglebraic equation solvers.'
  description: |
    scikit-SUNDAE provides Python bindings to SUNDIALS integrators. Specifically,
    it interfaces with the IDA and CVODE solvers. These are capable of efficiently
    solving ordinary differential equations and differential algebraic equations.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://scikit-sundae.readthedocs.io/
  dev_url: https://github.com/NREL/scikit-sundae

extra:
  recipe-maintainers:
    - c-randall
