{% set name = "scikit-sundae" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: f32d23812bccdff57bb61412f8213d59eb833e15860552e5afa64eee6dc1e5a2

build:
  script:
    - export SUNDIALS_PREFIX=$PREFIX          # [not win]
    - set "SUNDIALS_PREFIX=%LIBRARY_PREFIX%"  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py>313]

requirements:
  build:
    - python >=3.9,<3.14  # [build_platform != target_platform]
    - setuptools  # [build_platform != target_platform]
    - cython  # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]
    - packaging  # [build_platform != target_platform]
    - sundials >=7.5,<7.6  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python >=3.9,<3.14
    - setuptools
    - cython
    - numpy
    - libblas
    - pip
    - sundials >=7.5,<7.6
  run:
    - python >=3.9,<3.14
    - numpy
    - scipy
    - sundials >=7.5,<7.6

test:
  imports:
    - numpy
    - scipy
    - sksundae

about:
  home: https://github.com/NREL/scikit-sundae
  summary: Python bindings to SUNDIALS differential aglebraic equation solvers.
  description: |
    scikit-SUNDAE provides Python bindings to SUNDIALS integrators. Specifically,
    it interfaces with the IDA and CVODE solvers. These are capable of efficiently
    solving ordinary differential equations and differential algebraic equations.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://scikit-sundae.readthedocs.io/
  dev_url: https://github.com/NREL/scikit-sundae

extra:
  recipe-maintainers:
    - c-randall
